language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "nightly"

os:
  - linux
  - osx

matrix:
  fast_finish: true
  allow_failures:
    - python: nightly

install: python setup.py install

script: cd tests && ./run.sh
